name: rico_user_app
description: Rico User App - A Flutter application following best practices
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # UI & Navigation
  cupertino_icons: ^1.0.6
  go_router: ^12.1.3
  
  # State Management
  provider: ^6.1.1
  riverpod: ^2.4.9
  flutter_riverpod: ^2.4.9
  
  # Network & Data
  dio: ^5.4.0
  shared_preferences: ^2.2.2
  http: ^1.1.0
  
  # Utilities
  intl: ^0.18.1
  logger: ^2.0.2+1
  flutter_screenutil: ^5.9.0
  
  # Local Storage
  sqflite: ^2.3.0
  path: ^1.8.3
  path_provider: ^2.1.1
  
  # Image & Media
  image_picker: ^1.0.4
  cached_network_image: ^3.3.0
  
  # File Upload & Storage
  crypto: ^3.0.3
  mime: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  
  # Testing
  mockito: ^5.4.2
  build_runner: ^2.4.7

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
